// Comprehensive list of company types for the BuilderSuite Marketplace
// Organized by category with parent-child relationships (alphabetized within categories)

export const COMPANY_TYPE_CATEGORIES: Record<string, string[]> = {
  "Designers": [
    "Architect",
    "Bath Designer",
    "Closet Designer",
    "Home Theater Designer",
    "Interior Designer",
    "Kitchen Designer",
    "Landscape Architect",
    "Lighting Designer",
  ],
  "Engineers": [
    "Civil Engineer",
    "Electrical Engineer",
    "Environmental Engineer",
    "Fire Protection Engineer",
    "Geotechnical Engineer",
    "Mechanical Engineer",
    "MEP Engineer",
    "Plumbing Engineer",
    "Stormwater Engineer",
    "Structural Engineer",
    "Transportation Engineer",
  ],
  "Equipment Suppliers": [
    "Crane Rental",
    "Dumpster Rental",
    "Equipment Rental",
    "Generator Rental",
    "Heavy Equipment Rental",
    "Portable Toilet Rental",
    "Scaffolding Rental",
    "Tool Rental",
  ],
  "Exterior & Landscaping": [
    "Deck Contractor",
    "Driveway Contractor",
    "Exterior Painting Contractor",
    "Fence Contractor",
    "Garage Door Installer",
    "Gutter Contractor",
    "Irrigation Contractor",
    "Landscaping Contractor",
    "Lawn Care Service",
    "Outdoor Living Contractor",
    "Patio Contractor",
    "Paving Contractor",
    "Pool/Spa Contractor",
    "Pressure Washing Service",
    "Tree Service",
    "Window Cleaning Service",
  ],
  "Financial Services": [
    "Accountant/CPA",
    "Appraiser",
    "Commercial Lender",
    "Construction Lender",
    "Financial Advisor",
    "Insurance Agent",
    "Mortgage Lender",
    "Private Money Lender",
    "Surety Bond Provider",
    "Tax Consultant",
    "Title Company",
  ],
  "Government & Services": [
    "Arborist",
    "Energy Auditor",
    "Home Inspector",
    "Home Warranty Provider",
    "Mold Inspector",
    "Municipality/Permitting",
    "Real Estate Agent",
    "Termite Inspector",
    "Utility Company",
  ],
  "Interior Trades": [
    "Accent Wall Contractor",
    "Built-In Cabinet Installer",
    "Cabinet Installer",
    "Cabinet Manufacturer",
    "Carpet Installer",
    "Closet System Installer",
    "Countertop Fabricator",
    "Countertop Installer",
    "Decorative Painter/Faux Finisher",
    "Door Installer",
    "Drywall Contractor",
    "Finish Carpenter",
    "Flooring Contractor",
    "Hardwood Flooring Installer",
    "Insulation Contractor",
    "Interior Trim Contractor",
    "Millwork Installer",
    "Painter",
    "Shiplap Installer",
    "Spray Foam Contractor",
    "Stair Contractor",
    "Tile Contractor",
    "Vinyl/LVP Installer",
    "Wallpaper Installer",
    "Window Installer",
  ],
  "Legal Services": [
    "Business Attorney",
    "Construction Attorney",
    "Contract Attorney",
    "Environmental Attorney",
    "HOA Attorney",
    "Land Use Attorney",
    "Lien Attorney",
    "Real Estate Attorney",
    "Title Attorney",
    "Zoning Attorney",
  ],
  "Material Suppliers": [
    "Brick & Stone Supplier",
    "Building Materials Supplier",
    "Cabinet Supplier",
    "Concrete Supplier (Ready-Mix)",
    "Countertop Supplier",
    "Door & Window Supplier",
    "Drywall Supplier",
    "Electrical Fixtures Supplier",
    "Flooring Supplier",
    "Hardware Supplier",
    "Insulation Supplier",
    "Lumber Yard",
    "Millwork Supplier",
    "Paint Supplier",
    "Plumbing Fixtures Supplier",
    "Roofing Materials Supplier",
    "Steel Supplier",
    "Tile Supplier",
  ],
  "MEP Contractors": [
    "Audio/Video Installer",
    "Electrical Contractor",
    "Fire Sprinkler Contractor",
    "Generator Installer",
    "HVAC Contractor",
    "Low Voltage Contractor",
    "Plumbing Contractor",
    "Security System Installer",
    "Smart Home Installer",
    "Solar/Renewable Energy Contractor",
  ],
  "Site Work Contractors": [
    "Concrete Contractor",
    "Demolition Contractor",
    "Earthwork Contractor",
    "Erosion Control Contractor",
    "Excavation Contractor",
    "Foundation Contractor",
    "Grading Contractor",
    "Land Clearing Contractor",
    "Retaining Wall Contractor",
    "Septic System Installer",
    "Storm Water Management Contractor",
    "Utility Contractor",
  ],
  "Specialty Contractors": [
    "Brick Mason",
    "Chimney Contractor",
    "EIFS Contractor",
    "Elevator Installer",
    "Fireplace Installer",
    "Glass/Mirror Contractor",
    "Home Automation Contractor",
    "Metal Railing Contractor",
    "Shower Door Installer",
    "Stone Mason",
    "Stucco Contractor",
    "Waterproofing Contractor",
    "Wrought Iron Contractor",
  ],
  "Structural Trades": [
    "Deck Framing Contractor",
    "Floor Joist Installer",
    "Framing Contractor",
    "Lumber Framing Contractor",
    "Masonry Contractor",
    "Post-Frame Builder",
    "Roofing Contractor",
    "Siding Contractor",
    "Steel Fabricator",
    "Timber Frame Builder",
    "Truss Manufacturer",
  ],
};

// Flat list for validation and database purposes
export const COMPANY_TYPES = Object.values(COMPANY_TYPE_CATEGORIES).flat();

export type CompanyType = typeof COMPANY_TYPES[number];
