import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "./useAuth";
import { useToast } from "@/hooks/use-toast";

export interface TemplateArticle {
  num: number;
  title: string;
  body: string;
}

export const DEFAULT_ARTICLES: TemplateArticle[] = [
  { num: 1, title: "THE WORK", body: "Subcontractor shall furnish all labor, materials, equipment, supervision, transportation and services necessary to complete the Work described in Exhibit A – Scope of Work and the Contract Documents. Work shall comply with project drawings, applicable codes and regulations, and accepted industry standards. Subcontractor shall coordinate its work with Contractor and other trades." },
  { num: 2, title: "CONTRACT DOCUMENTS", body: "The Subcontract Documents consist of the following:\n• This Agreement\n• Exhibit A – Scope of Work\n• Exhibit B – Project Drawings\n• Exhibit C – General Requirements\n• Written Change Orders issued by Contractor" },
  { num: 3, title: "CONTRACT SUM", body: "The Contractor agrees to pay the Subcontractor the amounts stated in the Subcontract Summary for full performance of the Work. Payments will be made based on approved progress of the Work in accordance with the Contractor's payment procedures." },
  { num: 4, title: "PAYMENTS", body: "Invoices must be sent to our accounting department at ap@oldbridgeports.com, and payments will be made within thirty days of receipt." },
  { num: 5, title: "PROJECT SCHEDULE", body: "Time is of the essence. Subcontractor shall begin work within seven (7) days of written notice to proceed and maintain sufficient manpower and equipment to meet the project schedule. If Subcontractor falls behind schedule, Subcontractor shall provide additional labor, equipment or overtime at its own cost to recover lost time." },
  { num: 6, title: "CHANGE ORDERS", body: "Changes to the Work must be authorized in writing by the Contractor's Project Manager prior to performing the work." },
  { num: 7, title: "INSPECTIONS AND COORDINATION", body: "Subcontractor shall coordinate inspections for its work, notify Contractor prior to scheduling inspections, attend inspections, and correct deficiencies identified by inspectors. Costs resulting from failed inspections caused by Subcontractor shall be borne by Subcontractor." },
  { num: 8, title: "PERMITS AND COMPLIANCE", body: "Subcontractor shall obtain required trade permits and comply with all applicable local, state and federal laws including OSHA regulations." },
  { num: 9, title: "SAFETY", body: "Subcontractor shall maintain safe working conditions and comply with OSHA and project safety requirements. Required safety equipment including hard hats shall be worn at all times." },
  { num: 10, title: "CLEANUP", body: "Subcontractor shall keep work areas clean and remove debris generated by its work. Contractor may perform cleanup and deduct costs from payments owed if Subcontractor fails to maintain jobsite cleanliness." },
  { num: 11, title: "WARRANTY", body: "Subcontractor warrants that all work shall be free from defects in materials and workmanship for one (1) year following project completion. Subcontractor shall repair defective work at no cost to Contractor." },
  { num: 12, title: "DEFAULT", body: "If Subcontractor fails to perform according to this Agreement, Contractor may provide written notice, supplement the workforce, or terminate the subcontract. Costs resulting from Subcontractor default may be deducted from payments owed." },
  { num: 13, title: "INDEMNIFICATION", body: "Subcontractor shall defend, indemnify and hold harmless Contractor and Owner from claims, damages, losses or expenses arising from Subcontractor's work." },
  { num: 14, title: "TERMINATION", body: "Contractor may terminate this Agreement with ten (10) days written notice. Subcontractor shall be paid for properly completed work to the date of termination." },
];

export const DEFAULT_EXHIBITS = {
  projectDrawings: "Subcontractor shall perform work in accordance with approved civil, landscape and architectural drawings listed in the project drawing schedule.",
  generalRequirements: "Work Hours: Monday–Friday, 7:00 AM–5:00 PM. Subcontractor shall coordinate daily with Contractor, maintain a clean and safe jobsite, and follow project safety and delivery requirements.",
};

export const useTemplateContent = (templateKey: string) => {
  const { user } = useAuth();
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ["template-content", templateKey],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("template_content" as any)
        .select("*")
        .eq("template_key", templateKey)
        .maybeSingle();

      if (error) {
        console.error("Error fetching template content:", error);
        return null;
      }
      return data;
    },
    enabled: !!user,
  });

  const saveMutation = useMutation({
    mutationFn: async (content: { articles: TemplateArticle[]; exhibits: typeof DEFAULT_EXHIBITS }) => {
      if (!user) throw new Error("Not authenticated");

      // Get owner_id (either user's own id or their home_builder_id)
      const { data: userData } = await supabase
        .from("users")
        .select("role, home_builder_id")
        .eq("id", user.id)
        .single();

      const ownerId = userData?.role === "owner" ? user.id : userData?.home_builder_id;
      if (!ownerId) throw new Error("Could not determine owner");

      const { error } = await supabase
        .from("template_content" as any)
        .upsert(
          {
            owner_id: ownerId,
            template_key: templateKey,
            content: content,
            updated_by: user.id,
          },
          { onConflict: "owner_id,template_key" }
        );

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["template-content", templateKey] });
      toast({ title: "Template Saved" });
    },
    onError: (error) => {
      console.error("Error saving template:", error);
      toast({ title: "Error", description: "Failed to save template.", variant: "destructive" });
    },
  });

  const content = (data as any)?.content as { articles: TemplateArticle[]; exhibits: typeof DEFAULT_EXHIBITS } | undefined;

  return {
    articles: content?.articles ?? DEFAULT_ARTICLES,
    exhibits: content?.exhibits ?? DEFAULT_EXHIBITS,
    isLoading,
    save: saveMutation.mutate,
    isSaving: saveMutation.isPending,
  };
};
