-- Add missing check print settings columns for bank info, routing fraction, date label, and MICR line
ALTER TABLE public.check_print_settings
ADD COLUMN IF NOT EXISTS bank_name_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS bank_name_y NUMERIC DEFAULT 0.65,
ADD COLUMN IF NOT EXISTS bank_address_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS bank_address_y NUMERIC DEFAULT 0.80,
ADD COLUMN IF NOT EXISTS bank_city_state_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS bank_city_state_y NUMERIC DEFAULT 0.95,
ADD COLUMN IF NOT EXISTS routing_fraction_x NUMERIC DEFAULT 7.0,
ADD COLUMN IF NOT EXISTS routing_fraction_y NUMERIC DEFAULT 0.65,
ADD COLUMN IF NOT EXISTS date_label_x NUMERIC DEFAULT 4.5,
ADD COLUMN IF NOT EXISTS date_label_y NUMERIC DEFAULT 1.0,
ADD COLUMN IF NOT EXISTS micr_check_number_x NUMERIC DEFAULT 0.5,
ADD COLUMN IF NOT EXISTS micr_check_number_y NUMERIC DEFAULT 3.2,
ADD COLUMN IF NOT EXISTS micr_routing_x NUMERIC DEFAULT 2.5,
ADD COLUMN IF NOT EXISTS micr_routing_y NUMERIC DEFAULT 3.2,
ADD COLUMN IF NOT EXISTS micr_account_x NUMERIC DEFAULT 4.5,
ADD COLUMN IF NOT EXISTS micr_account_y NUMERIC DEFAULT 3.2;