-- Add additional position fields for exact check replication
ALTER TABLE public.check_print_settings 
ADD COLUMN IF NOT EXISTS company_line2_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS company_line2_y NUMERIC DEFAULT 0.50,
ADD COLUMN IF NOT EXISTS company_line3_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS company_line3_y NUMERIC DEFAULT 0.65,
ADD COLUMN IF NOT EXISTS company_line4_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS company_line4_y NUMERIC DEFAULT 0.80,

-- Bank lines (3 lines)
ADD COLUMN IF NOT EXISTS bank_line2_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS bank_line2_y NUMERIC DEFAULT 1.10,
ADD COLUMN IF NOT EXISTS bank_line3_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS bank_line3_y NUMERIC DEFAULT 1.25,

-- PAY / TO THE / ORDER OF labels
ADD COLUMN IF NOT EXISTS pay_label_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS pay_label_y NUMERIC DEFAULT 1.80,
ADD COLUMN IF NOT EXISTS to_the_label_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS to_the_label_y NUMERIC DEFAULT 1.95,
ADD COLUMN IF NOT EXISTS order_of_label_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS order_of_label_y NUMERIC DEFAULT 2.10,

-- Payee address lines
ADD COLUMN IF NOT EXISTS payee_line2_x NUMERIC DEFAULT 0.65,
ADD COLUMN IF NOT EXISTS payee_line2_y NUMERIC DEFAULT 2.05,
ADD COLUMN IF NOT EXISTS payee_line3_x NUMERIC DEFAULT 0.65,
ADD COLUMN IF NOT EXISTS payee_line3_y NUMERIC DEFAULT 2.20,
ADD COLUMN IF NOT EXISTS payee_line4_x NUMERIC DEFAULT 0.65,
ADD COLUMN IF NOT EXISTS payee_label_y NUMERIC DEFAULT 2.35,

-- Signature label
ADD COLUMN IF NOT EXISTS signature_label_x NUMERIC DEFAULT 5.5,
ADD COLUMN IF NOT EXISTS signature_label_y NUMERIC DEFAULT 2.8,

-- MultiCHAX (blank for now)
ADD COLUMN IF NOT EXISTS multichax_x NUMERIC DEFAULT 0.25,
ADD COLUMN IF NOT EXISTS multichax_y NUMERIC DEFAULT 0.20,

-- Amount words line (for the written amount)
ADD COLUMN IF NOT EXISTS amount_words_line_x NUMERIC DEFAULT 0.75,
ADD COLUMN IF NOT EXISTS amount_words_line_y NUMERIC DEFAULT 2.45;